{{- if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mongodb.secretName" . }}
  labels: {{- include "mongodb.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.auth.keys.rootPassword }}: {{ required "auth.rootPassword is required when auth.existingSecret is empty" .Values.auth.rootPassword | quote }}
  {{ .Values.auth.keys.appPassword }}: {{ required "auth.appPassword is required when auth.existingSecret is empty" .Values.auth.appPassword | quote }}
  {{ .Values.auth.keys.metricsPassword }}: {{ required "auth.metricsPassword is required when auth.existingSecret is empty" .Values.auth.metricsPassword | quote }}
  {{ .Values.auth.keys.keyfile }}: {{ required "auth.keyfile is required when auth.existingSecret is empty" .Values.auth.keyfile | quote }}
{{- end }}
